services:
  venueless:
    image: 'venueless/venueless:stable'
    container_name: venueless
    restart: always
    ports:
      - "9007:80"
    volumes:
      - ./.docker/volumes/conf:/etc/venueless
    depends_on:
      - db
    networks:
      - stack_network
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./.docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=venueless
      - POSTGRES_USER=venueless
      - POSTGRES_PASSWORD=venueless
    networks:
      - stack_network
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - stack_network

networks:
  stack_network:
    external: false
