services:
  venueless:
    image: 'venueless/venueless:stable'
    container_name: venueless
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./.docker/volumes/conf:/etc/venueless
      - ./.docker/volumes/data:/data
    depends_on:
      - db
      - redis
  db:
    image: postgres
    container_name: venueless-db
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./.docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:
    image: redis:latest
    container_name: venueless-redis
    restart: always
